backend:
  name: git-gateway
  branch: master
site_url: "https://github.com/quantum-t/quantum-web"
media_folder: "src/images"
public_folder: "/images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        delete: false
        file: "src/index.md"
        slug: "{{slug}}"
        create: false
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/home.njk"}
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Title Image", name: "titleImage", widget: "image", required: false}
          - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
          - {label: "Hero Image", name: "heroImage", widget: "image", required: false}
          - {label: "Hero Image Description", name: "heroImageAlt", widget: "string", required: false}
          - {label: "Social Image", name: "socialImage", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "generic_pages"
    label: "Generic Pages"
    folder: "src/pages"
    slug: "{{slug}}"
    preview_path: "pages/{{slug}}"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/page.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink Override (Pattern: '/your-slug/index.html')", name: "permalink", widget: "string", required: false}
      - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
      - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
      - {label: "Social Image", name: "socialImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Globals"
    name: "globals"
    files:
      - label: "Site Data"
        name: "site_data"
        delete: false
        file: "src/_data/site.json"
        fields:
          - {label: "Site Name", name: "name", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "siteNameSVG", name: "nameSVG", widget: "code", default_language: "svg", allow_language_selection: false }
          - {label: "Site Url", name: "url", widget: "string"}
          - {label: "Author Name", name: "authorName", widget: "string"}
          - {label: "Author Email Address", name: "authorEmail", widget: "string"}
          - {label: "Author Twitter Handle", name: "authorHandle", widget: "string", required: false}
          - {label: "Footer Short Description", name: "shortDesc", widget: "string"}
          - {label: "Maximum Posts Per Page", name: "maxPostsPerPage", widget: "number", default: 5}
          - {label: "Show Theme Credit", name: "showThemeCredit", widget: "boolean", default: true}
          - {label: "Enable Third Party Comments Area", name: "enableThirdPartyComments", widget: "boolean", default: false}
          - {label: "Payment Pointer (Web Monetization: https://bit.ly/2kTRI1b)", name: "paymentPointer", widget: "string"}
          - {label: "Favicon", name: "faviconPath", widget: "image"}
      - label: "Navigation"
        name: "nav"
        delete: false
        file: "src/_data/navigation.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
              - {label: "Is url to external site?", name: "external", widget: "boolean", required: false}
      - label: "Theme Settings"
        name: "theme"
        delete: false
        file: "src/_data/tokens.json"
        fields:
          - label: "Size Scale"
            name: "size-scale"
            widget: "object"
            fields: 
              - {label: "Base Size", name: "base", widget: "string", default: "1rem"}
              - {label: "Ratio: 300", name: "300", widget: "string", default: "0.8rem"}
              - {label: "Ratio: 500", name: "500", widget: "string", default: "1.25rem"}
              - {label: "Ratio: 600", name: "600", widget: "string", default: "1.56rem"}
              - {label: "Ratio: 700", name: "700", widget: "string", default: "1.95rem"}
              - {label: "Ratio: 800", name: "800", widget: "string", default: "2.44rem"}
              - {label: "Ratio: 900", name: "900", widget: "string", default: "3.05rem"}
              - {label: "Max Size", name: "max", widget: "string", default: "4rem"}
          - label: "Colors"
            name: "colors"
            widget: "object"
            fields: 
              - {label: "Primary", name: "primary", widget: "string", default: "hsl(208, 57%, 21%)"}
              - {label: "Primary Shade (darker)", name: "primary-shade", widget: "string", default: "hsl(208, 56%, 14%)"}
              - {label: "Primary Glare (lighter)", name: "primary-glare", widget: "string", default: "hsl(207, 57%, 31%)"}
              - {label: "Highlight", name: "highlight", widget: "string", default: "hsl(42, 98%, 77%)"}
              - {label: "Light", name: "light", widget: "string", default: "hsl(0, 0%, 100%)"}
              - {label: "Mid", name: "mid", widget: "string", default: "hsl(0, 0%, 80%)"}
              - {label: "Dark", name: "dark", widget: "string", default: "hsl(0, 0%, 20%)"}
              - {label: "Slate", name: "slate", widget: "string", default: "hsl(0, 0%, 25%)"}
          - label: "Fonts"
            name: "fonts"
            widget: "hidden"
            default: { "base": "\"-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'\"", "serif": "\"'Lora', serif\""}
  - label: "references"
    name: "references"
    files:
      - label: "References"
        name: "references"
        delete: false
        file: "src/_data/references.json"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/inspiration.njk"}
          - label: "reference"
            name: "reference"
            widget: "list"
            fields:
              - {label: "referee Name", name: "refereeName", widget: "string", required: false}
              - {label: "referee Title", name: "refereeTitle", widget: "string", required: false}
              - {label: "background Image", name: "background", widget: "image", required: false}
              - {label: "quote", name: "quote", widget: "string"}
              - {label: "Show Button", name: "showButton", widget: "boolean", required: false}
              - {label: "on homepage", name: "onHomepage", widget: "boolean", required: false}  
  - name: "programs"
    label: "programs"
    folder: "src/programs"
    slug: "{{slug}}"
    preview_path: "programs/{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "price", name: "programPrice", widget: "string"}
      - {label: "showPrice", name: "showPrice", widget: "boolean", required: false}
      - {label: "tags", name: "tags", widget: "hidden", default: "program"}
      - {label: "Button Text", name: "btnText", widget: "string", default: "Enquire Now"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "inspiration"
    name: "inspiration"
    files:
      - label: "inspiration"
        name: "inspiration"
        delete: false
        file: "src/_data/inspiration.json"
        fields:
          - label: "inspire"
            name: "inspire"
            widget: "list"
            fields:
              - {label: "quote", name: "quote", widget: "string"}
              - {label: "source", name: "source", widget: "string", required: false}
              - {label: "background Image", name: "background", widget: "image", required: false}
              - {label: "Show Button", name: "showButton", widget: "boolean", required: false}
              - {label: "on homepage", name: "onHomepage", widget: "boolean", required: false}
  - label: "inputs"
    name: "inputs"
    file: "src/forms/input_types.json"
    fields: 
      - label: "field Type"
      - name: "type"
      - widget: "string"
  - label: "forms"
    name: "forms"
    folder: "src/forms"
    create: true
    identifier_field: "formName"
    fields:
      - {label: "formName", name: "formName", widget: "string"}
      - {label: "honeyPot", name: "honeyPot", widget: "string"}
      - {label: "submitButton", name: "submitButton", widget: "string", required: false}
      - label: "input"
        name: "input"
         widget: "list"
         fields:
           - label: "inputType"
              name: "type"
              widget: "relation"
              collection: "inputs"
              default: "text"
              searchFields: "type"
              valueFields: "type"
              displayFields: "type"
      
      